import {beforeEach,afterAll,describe,it,expect,vi} from 'vitest';import request from 'supertest';
process.env.NODE_ENV='test';process.env.DATABASE_PATH=':memory:';process.env.JWT_SECRET='test-secret-that-is-at-least-32-characters';process.env.GOOGLE_CLIENT_ID='test-google-client';
vi.mock('google-auth-library',()=>({OAuth2Client:class{async verifyIdToken({idToken}){if(idToken.startsWith('invalid'))throw new Error('Invalid token');return {getPayload:()=>({sub:'google-123',email:'a@test.com',email_verified:true,iss:'https://accounts.google.com',name:'Google User',picture:'https://example.com/avatar.png'})}}}}));
const {createApp}=await import('../src/app.js');const {getDb,closeDb}=await import('../src/db/index.js');const app=createApp();
const register=async(email='a@test.com')=>(await request(app).post('/api/auth/register').send({name:'Test User',email,password:'Password1'})).body.data;
beforeEach(()=>{const db=getDb();for(const t of ['transactions','budgets','savings_goals','recurring_commitments','users'])db.prepare(`DELETE FROM ${t}`).run();});afterAll(closeDb);
describe('authentication and isolation',()=>{it('registers, logs in and protects routes',async()=>{const a=await register();expect(a.token).toBeTruthy();expect((await request(app).get('/api/dashboard')).status).toBe(401);expect((await request(app).post('/api/auth/login').send({email:'a@test.com',password:'Password1'})).status).toBe(200);});it('rejects duplicates and invalid JWTs',async()=>{await register();expect((await request(app).post('/api/auth/register').send({name:'Again',email:'a@test.com',password:'Password1'})).status).toBe(409);expect((await request(app).get('/api/dashboard').set('Authorization','Bearer tampered')).status).toBe(401);});it('isolates every user record',async()=>{const a=await register('a@test.com'),b=await register('b@test.com');const made=await request(app).post('/api/transactions').set('Authorization',`Bearer ${a.token}`).send({type:'expense',description:'Private',category:'Other',amount:10,date:'2026-09-23',note:''});const id=made.body.data.transaction.id;expect((await request(app).get(`/api/transactions/${id}`).set('Authorization',`Bearer ${b.token}`)).status).toBe(404);expect((await request(app).put(`/api/transactions/${id}`).set('Authorization',`Bearer ${b.token}`).send({type:'expense',description:'Hack',category:'Other',amount:1,date:'2026-09-23',note:''})).status).toBe(404);expect((await request(app).delete(`/api/transactions/${id}`).set('Authorization',`Bearer ${b.token}`)).status).toBe(404);});});
describe('finance APIs',()=>{it('handles CRUD and dashboard/budget calculations',async()=>{const {token}=await register(),h={Authorization:`Bearer ${token}`};let t=await request(app).post('/api/transactions').set(h).send({type:'income',description:'Salary',category:'Salary',amount:50000,date:'2026-09-23',note:''});expect(t.status).toBe(201);await request(app).post('/api/transactions').set(h).send({type:'expense',description:'Food',category:'Food',amount:1000,date:'2026-09-23',note:''});let b=await request(app).post('/api/budgets').set(h).send({category:'Food',monthlyLimit:5000,month:9,year:2026});expect(b.status).toBe(201);b=await request(app).get('/api/budgets?month=9&year=2026').set(h);expect(b.body.data.budgets[0]).toMatchObject({spent:1000,remaining:4000,percentage:20});const d=await request(app).get('/api/dashboard').set(h);expect(d.body.data.summary).toMatchObject({balance:49000,totalIncome:50000,totalExpenses:1000});t=await request(app).delete(`/api/transactions/${t.body.data.transaction.id}`).set(h);expect(t.status).toBe(204);});it('creates goals and recurring commitments',async()=>{const {token}=await register(),h={Authorization:`Bearer ${token}`};const g=await request(app).post('/api/goals').set(h).send({name:'Fund',targetAmount:10000,savedAmount:2500,dueDate:'2027-01-01',description:''});expect(g.body.data.goal.percentage).toBe(25);const c=await request(app).post('/api/recurring').set(h).send({name:'Rent',amount:15000,category:'Housing',frequency:'monthly',nextDueDate:'2026-10-01',note:'',active:true});expect(c.status).toBe(201);expect((await request(app).get('/api/recurring').set(h)).body.data.recurring).toHaveLength(1);});});
describe('Google auth',()=>{it('verifies and safely links an existing email',async()=>{await register('a@test.com');const response=await request(app).post('/api/auth/google').send({credential:'valid-google-token-credential-12345'});expect(response.status).toBe(200);expect(response.body.data.user.authProvider).toBe('both');expect(getDb().prepare('SELECT COUNT(*) count FROM users').get().count).toBe(1);expect((await request(app).post('/api/auth/google').send({credential:'invalid-google-token-credential'})).status).toBe(401);});});
